### PR TITLE
Split into graph, graph-lib and graph-doc

### LINKED ISSUE #35: depends on racket-doc
For people who are using racket-minimal it would be really nice if `graph` could depend on `graph-lib` and `graph-doc`, where only `graph-lib` would be necessary for compiling depending code, and only `graph-doc` would depend on the heavy and circular `racket-doc`.

### PR DESCRIPTION
**Pull request by clacke**
I modeled the split after how net, net-lib and net-doc do it.

 - graph is an abstract package that just depends on the others.
 - graph-lib has the actual code.
 - graph-doc has the documentation and has the heavy racket-doc dependency.
 - Moved graph.scrbl into subdirectory scribblings.

Closes #35

### CODE REVIEW

**Comment by clacke** [comment]
It seems that Racket 5 does not allow multiple packages to write into the same collection.

**Comment by clacke** [comment]
Correction: Racket 5 doesn't allow multiple packages to have an info.rkt in the same collection. I will see if the scribble builds without the info.rkt. `net-lib` in Racket 5.9 has no info.rkt in its collection directory.

**Comment by clacke** [comment]
It doesn't. Hm.

**Comment by clacke** [comment]
I asked the List for guidance: https://www.mail-archive.com/racket-users@googlegroups.com/msg39297.html

**Comment by stchang** [comment]
Sorry for the long delay, but I'm working to merge this now.

**Comment by stchang** [comment]
Done in 6c3551757af973e9db9585b894ca83f3db3de3db.

Thanks for all your effort!

**Pull request closed without merging**
